# Stage 1 → build React app
FROM node:20 AS build
WORKDIR /app
 
COPY my-react-app/package*.json ./
RUN npm install
 
COPY my-react-app .
RUN npm run build
 
# Stage 2 → serve using nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80