name: React + Podman CI
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build-container:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Check Podman
        run: podman --version
 
      - name: Build React image
        run: podman build -t my-react-app:latest .